# -*- coding: utf-8 -*-
"""deepface.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/13RXB423SookNT8fPzcO59KdGHGYrxaXn
"""

from deepface import DeepFace

try:
  analysis = DeepFace.analyze(img_path = "/content/unnamed.jpg", actions = ["gender"]) #mnist image
except ValueError:
  pass


verification = DeepFace.verify(img1_path = "dua_lipa1.jpg", img2_path = "dua_lipa2.jpg")

BinaryVerification = verification['verified']