# -*- coding: utf-8 -*-
"""Untitled24.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1-AlfOwA9vhnZaZJ-bJGln1Nv5mplyxna
"""

from deepface import DeepFace

try:
  analysis = DeepFace.analyze(img_path = "EnemiesOfSyntax_AIML_01/load_model_img/load_model.jpg", actions = ["gender"]) #mnist image
except ValueError:
  pass

analysis = DeepFace.analyze(img_path = r"C:\Users\ariha\Desktop\COC\datasouls_antispoof\datasouls_antispoof\real_1.jpg", actions = ["gender"]) #actual image

gender = analysis[0]['dominant_gender']

male = 'male'
female = 'female'

def gender_reveal(gender):
  if gender == 'Woman':
    return female
  if gender == 'Man':
    return male

sex = gender_reveal(gender)
print(sex)