# Generated by Django 4.1.1 on 2023-03-04 19:37

from django.db import migrations, models
import imageface.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to=imageface.models.upload_path)),
            ],
        ),
    ]
